# Generated by Django 2.0.7 on 2018-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20180710_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='currency_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ManyToManyField(to='contracts.Company'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ManyToManyField(to='contracts.Contract_type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency_type',
            field=models.ManyToManyField(to='contracts.Currency'),
        ),
    ]
