# Generated by Django 2.0.7 on 2018-07-10 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20180710_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contracts.Company'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract_type'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contract',
            name='currency_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='currency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contracts.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
