# Generated by Django 2.0.7 on 2018-07-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20180710_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
